### ISSUE TITLE
keycloak-gatekeeper 1.1.1 is missing on hub.helm.sh / the helm repo

### ISSUE THREAD

**Issue by monotek** [gabibbo97/charts#11]
Seems there is some problem with the chart deployment.
The old keycloak-gatekeeper version 1.1.1 was just deleted / replaced by 1.2.0.
Now our deployments fail. 
Old versions should never be deleted from the repo.

**Comment by gabibbo97** [comment]
Hi, I had made a mistake in the continuous delivery pipeline, it should be fixed now.

This commit https://github.com/gabibbo97/charts/commit/5f293be0d6ba4d299eb58dc6609ac3699929a8fe should have now all of the repos

I have used https://github.com/gabibbo97/charts/blob/44c6f8b11519826f1036e706d59ff4492e1c0bfe/scripts/recreate-repo.sh this script to fix

**Comment by monotek** [comment]
Thanks a lot. 
All versions are back now :-)

https://hub.helm.sh/charts/gabibbo97/keycloak-gatekeeper
