### ISSUE TITLE
keycloak-gatekeeper - image does not exist

### ISSUE THREAD

**Issue by monotek** [gabibbo97/charts#13]
The used image 4.8.0.Final (https://github.com/gabibbo97/charts/blob/master/charts/keycloak-gatekeeper/values.yaml#L9) does not exist in the docker registry. 

See: https://hub.docker.com/r/keycloak/keycloak-gatekeeper/tags

If i try to use image 6.0.1 the container crashes with:
`[error] invalid options, flag provided but not defined: -Dkeycloak.profile.feature.authz_drools_policy
`

edit: adding "droolsPolicyEnabled: false" to the values file fixed the issue. 
imho it should be disabled by default.

**Comment by gabibbo97** [comment]
They somehow removed the tag, this also hit my deployments
