### ISSUE TITLE
helm install issue

### ISSUE THREAD

**Issue by prasad-1729** [gabibbo97/charts#26]
while running "**helm install <name> gabibbo97/periodic-daemonset --version 1.0.1**"

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec): unknown field "ttlSecondsAfterFinished" in io.k8s.api.batch.v1.JobSpec

**Comment by gabibbo97** [comment]
Is your cluster running with the correct feature gate ?

See https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by prasad-1729** [comment]
Thank you..for quick help..
do you know how to enable feature gate..can you please help..??

**Comment by gabibbo97** [comment]
What k8s distro are you using?

**Comment by gabibbo97** [comment]
Hi, I've just pushed https://github.com/gabibbo97/charts/commit/d25ead8aec501f7776df8e6f99f46e3309a1ff0b

Can you try it out with `helm install gabibbo97/periodic-daemonset --version 1.0.2 --set ttlSecondsAfterFinished=''` ?

**Comment by prasad-1729** [comment]
Thank you...it successfully installed..!!

**Comment by gabibbo97** [comment]
Can I close the issue then?

**Comment by prasad-1729** [comment]
Thanks!!
