### ISSUE TITLE
gabibbo97.github.io/charts/ is gone 404

### ISSUE THREAD

**Issue by tobstone** [gabibbo97/charts#31]
https://gabibbo97.github.io/charts/ returns only 404

**Comment by gabibbo97** [comment]
There is no public facing HTML index, there, if you try to access the Helm index https://gabibbo97.github.io/charts/index.yaml or directly a chart https://gabibbo97.github.io/charts/389ds-0.1.0.tgz it should work, I could probably add a redirect in there to clarify this

**Comment by tobstone** [comment]
there was a hiccup, the index.yaml wasnt reachable too, but now its fine again
