### ISSUE TITLE
script scope mapper absence in latest keycloak versions

### ISSUE THREAD

**Issue by y0zg** [gabibbo97/charts#33]
In latest keycloak versions there is no script scope mapper anymore, this option allowed to fix 403 error referenced: https://hub.helm.sh/charts/gabibbo97/keycloak-gatekeeper

More details:
https://stackoverflow.com/questions/62199404/keycloak-script-mapper-option-missing-in-9-0-3

What is the proper option apart of restarting keycloak with `-Dkeycloak.profile.feature.upload_scripts=enabled` in order to fix access issue via gatekeeper?

Thank you

**Comment by y0zg** [comment]
when I add this paramter into `values.yaml`

```
## Overrides the default args for the Keycloak container
args: 
- -Dkeycloak.profile.feature.upload_scripts=enabled
```

I cannot access keycloak anymore, any idea what might me the root cause?

pod is started well and I can access it via `kubectl exec`, logs are also in good condition

ERROR after trying to access via `port-forward`:

```
k port-forward svc/keycloak-test-http -n keycloak-test 8080:80

E0810 16:11:44.265165   18500 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod d2046a71f0c0e0818402c1c54a08f76fc72986ac4f724aa91a49e92ac94d619d, uid : failed to execute portforward in network namespace "/var/run/netns/cni-58baccc9-e090-7a02-bce1-386caceea33a": socat command returns error: exit status 1, stderr: "2020/08/10 13:11:44 socat[101153] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused\n"
Handling connection for 8080
```

@gabibbo97  Could you please advise?

**Comment by gabibbo97** [comment]
Hello which version of Keycloak are you using?
I'm using 11 and the way I package my JS script is roughly by following this workflow:

1. Put all your scripts in a directory
2. Create a directory META-INF
3. Inside it create a `keycloak-scripts.json` like in the [docs](https://www.keycloak.org/docs/latest/server_development/#create-a-jar-with-the-scripts-to-deploy)
4. Zip the entire folder (scripts + META-INF)
5. Change the extension to `.jar`
6. After that I have a Dockerfile like so

```dockerfile
FROM busybox
COPY my-keycloak-scripts.jar /keycloak-scripts.jar
ENTRYPOINT cp /keycloak-scripts.jar /dest
```
7. Add that container as an initContainer
8. Modify your keycloak deployment such that you have an emptydir shared between keycloak and the initcontainer (in the initcontainer you have to mount it to `/dest` and in keycloak you have to mount it in `standalone/deployments` relative to where Keycloak is)

The old way of uploading scripts via console I think has been removed so I have no idea if it is still working, even with the flag you mentioned.

Sorry for taking a long time but I've been super busy at work

**Comment by y0zg** [comment]
Thank you for answer @gabibbo97 

I migrated Keycloak from ver.7 to ver.11 and currently see problems to integrate newer version of Keycloak with your helm chart  as  **Troubleshooting** section in  https://hub.helm.sh/charts/gabibbo97/keycloak-gatekeeper  needs Script Mapper functionality.  Is above solution with initContainer the only way to make keycloak 11 working with your helm chart?

**Comment by y0zg** [comment]
keycloak deployment with these options solved the issue
```
args:
- -b 0.0.0.0
- -Dkeycloak.profile.feature.upload_scripts=enabled
```

**Comment by gabibbo97** [comment]
https://www.keycloak.org/docs/latest/server_installation/#profiles please be aware that they might remove it in the future!

**Comment by y0zg** [comment]
@gabibbo97 do you have any other ideas how to make keycloak gatekeeper helm chart working with keycloak version 11?

**Comment by y0zg** [comment]
It seems Audience Mapper type solves 403 issue as well
