### ISSUE TITLE
how to set logging for dex to debug?

### ISSUE THREAD

**Issue by ieugen** [gabibbo97/charts#38]
It's my first time deploying dex and I would like to enable debug logging.
I've noticed that I can do that like this:

https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml
```
# Options for controlling the logger.
# logger:
#   level: "debug"
#   format: "text" # can also be "json"
```

However it does not seem possible to do that using this chart: 
https://github.com/gabibbo97/charts/blob/master/charts/dex/templates/config.yaml#L21 

As a general observation: Dex configuration seems pretty hard to do with this chart. 
Is there a reason why the configuration is done via fragments of yaml part of the chart? 
Would it be easier to just put an entire, plain dex configuration ? 

p.s. I'm using configuration management (ansible) to deploy and it would be great if I can setup the full config at deploy time instead of editing the config map after.

Thanks,
Eugen

**Comment by gabibbo97** [comment]
It was built like so in order to split up configmaps and secrets for environment and to cater to "plug and play users"
If you are orchestrating It could make more sense to override the entirety of the configmap.

I'll take a look at this and expand the scope of the chart accordingly

**Comment by gabibbo97** [comment]
Hi, is https://github.com/gabibbo97/charts/commit/f928d84e0fa5bb7cc81304b28aa7fb5b129f4cd6 what you were looking for?

**Comment by ieugen** [comment]
Thanks, looks good to me :)

**Comment by ieugen** [comment]
works nicely. 
Thank you @gabibbo97
