### ISSUE TITLE
cannot find 'client_id' in 'aud' claim

### ISSUE THREAD

**Issue by Nuru** [gabibbo97/charts#9]
Installing this chart according to the documentation, access fails with the following error:
```
error unable to verify the id token	{"error": "oidc: JWT claims invalid: invalid claims, cannot find 'client_id' in 'aud' claim, aud=[master-realm account], client_id=myclientid"}
```
This is probably a configuration error, but the proper configuration to avoid this problem should be documented here.

**Comment by Nuru** [comment]
Turns out this is a known issue. Issue and workarounds described at https://issues.jboss.org/browse/KEYCLOAK-8954

**Comment by gabibbo97** [comment]
Hey, I can't access the link you provided, RedHat SSO is giving me errors.
Is it urgent or might I release the fix together with an updated version?

**Comment by Nuru** [comment]
The issue URL can be viewed anonymously, so I don't know why you could not access it. It has workarounds for the bug. This is not something you can fix in this chart, but it would be nice to add it to the documentation somehow.

**Comment by gabibbo97** [comment]
Let me know if I have addressed your concerns

**Comment by Nuru** [comment]
@gabibbo97 Yes, you have addressed my concerns with the update to the README. Thank you.
